# Generated by Django 4.2.5 on 2025-12-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_menu_id', models.IntegerField()),
                ('main_menu_name', models.CharField(max_length=255)),
                ('main_menu_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'main_menu',
            },
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_menu_id', models.IntegerField(blank=True, null=True)),
                ('sub_menu_id', models.IntegerField(blank=True, null=True)),
                ('sub_menu_type', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_menu_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_menu_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sub_menu',
            },
        ),
    ]
