# Generated by Django 4.2.5 on 2025-11-26 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myormlianxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '作者', 'verbose_name_plural': '作者列表'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '书籍', 'verbose_name_plural': '书籍列表'},
        ),
        migrations.AlterModelOptions(
            name='bookstore',
            options={'verbose_name': '书店', 'verbose_name_plural': '书店列表'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': '库存记录', 'verbose_name_plural': '库存记录列表'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': '出版社', 'verbose_name_plural': '出版社列表'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': '书籍评论', 'verbose_name_plural': '书籍评论列表'},
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(verbose_name='作者简介'),
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='电子邮箱'),
        ),
        migrations.AlterField(
            model_name='author',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否活跃'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100, verbose_name='作者姓名'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='myormlianxi.author', verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('FIC', '小说'), ('SCI', '科幻'), ('MYS', '悬疑'), ('BIO', '传记'), ('HIS', '历史'), ('SCI', '科学')], max_length=3, verbose_name='书籍类型'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=13, unique=True, verbose_name='ISBN编号'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(verbose_name='页数'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='售价'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(verbose_name='出版日期'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='myormlianxi.publisher', verbose_name='出版社'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, verbose_name='书籍标题'),
        ),
        migrations.AlterField(
            model_name='bookstore',
            name='books',
            field=models.ManyToManyField(related_name='bookstores', through='myormlianxi.Inventory', to='myormlianxi.book', verbose_name='关联书籍'),
        ),
        migrations.AlterField(
            model_name='bookstore',
            name='location',
            field=models.CharField(max_length=200, verbose_name='书店地址'),
        ),
        migrations.AlterField(
            model_name='bookstore',
            name='name',
            field=models.CharField(max_length=100, verbose_name='书店名称'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myormlianxi.book', verbose_name='关联书籍'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='bookstore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myormlianxi.bookstore', verbose_name='关联书店'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='last_restocked',
            field=models.DateTimeField(auto_now=True, verbose_name='最后补货时间'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='库存数量'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='address',
            field=models.TextField(verbose_name='出版社地址'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='founded_year',
            field=models.IntegerField(verbose_name='成立年份'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=200, verbose_name='出版社名称'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='website',
            field=models.URLField(verbose_name='官方网站'),
        ),
        migrations.AlterField(
            model_name='review',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='myormlianxi.book', verbose_name='关联书籍'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='是否已验证'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1星'), (2, '2星'), (3, '3星'), (4, '4星'), (5, '5星')], verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer_name',
            field=models.CharField(max_length=100, verbose_name='评论者姓名'),
        ),
    ]
