# Generated by Django 4.2.5 on 2025-11-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myormlianxi', '0002_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('sex', models.BooleanField(default=False, verbose_name='性别')),
            ],
            options={
                'verbose_name': 'model_demo',
                'verbose_name_plural': 'model_demo',
                'db_table': 'model_demo',
            },
        ),
    ]
