# Generated by Django 4.2.5 on 2025-11-27 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myormlianxi', '0003_modeldemo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FemaleUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myormlianxi.modeldemo',),
        ),
        migrations.CreateModel(
            name='MaleUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myormlianxi.modeldemo',),
        ),
    ]
