"""
Django settings for muxishop project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE_DIR / "apps"))  # 将 apps 的绝对路径加入到环境变量中

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2oq)q-pmjzb=ths1ga2bvnoy+btb59id2thztjgl5469$*zzf!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',  # DRF 框架
    'corsheaders',  # 跨域配置
    # 注册子应用
    "apps.address",
    "apps.cart",
    "apps.comment",
    "apps.goods",
    "apps.menu",
    "apps.order",
    "apps.user",
    "apps.pay",
    "apps.tools",
]

# 允许所有域名跨域 cors_origin_allow_all = true
CORS_ORIGIN_ALLOW_ALL = True
# 允许携带cookie cors_allow_credentials
CORS_ALLOW_CREDENTIALS = True

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # 配置跨域
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'muxishop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'muxishop.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    "default": {

        # 使用链接 mysql 的时候提示：Error loading MySQLdb module.
        # 需要在项目主目录的__init__.py中添加
        # from pymysql import install_as_MySQLdb
        # install_as_MySQLdb()
        # 用来让 pymysql 以 MySQLdb 的方式来对接 ORM

        "ENGINE": "django.db.backends.mysql",  # ORM的底层对接pymysql的核心引擎类
        "NAME": "muxishop",
        "HOST": "127.0.0.1",
        "PORT": 3306,
        "USER": "root",
        "PASSWORD": "123",
        'POOL_OPTIONS': {  # pool表示数据库连接池配置，主要为了节省连接数据库的开销，临时存储数据库连接对象
            'POOL_SIZE': 10,  # 默认情况下，打开的数据库连接对象的数量 [1,2,3,4,5,6,7,8,9,10]
            'MAX_OVERFLOW': 30,  # 负载情况下，允许溢出的连接数量  [11,12,13,14,15,16,17,18,19,20]
        }
    },
}

# CACHES = {
#     'default': {
#         'BACKEND': 'django_redis.cache.RedisCache',
#         'LOCATION': 'redis://127.0.0.1:6379/1',  # Redis地址，/1表示使用1号数据库
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#             'CONNECTION_POOL_KWARGS': {'max_connections': 100},
#             'PASSWORD': '',  # 如果有密码的话
#             'SOCKET_CONNECT_TIMEOUT': 5,  # 连接超时时间（秒）
#         },
#         'KEY_PREFIX': 'muxishop_captcha',  # 缓存key前缀
#     }
# }
# 添加 redis 缓存
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",  # select 1 选择 1 redis 库
        "TIMEOUT": 60,  # 设置超时时间，默认5分钟
        # 'KEY_PREFIX': 'muxishop_captcha',  # 缓存key前缀
    }
}

# 设置验证码过期时间（秒）
CAPTCHA_EXPIRE_TIME = 5 * 60  # 5分钟

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

# 语言
LANGUAGE_CODE = "zh-hans"
# 时区
TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# 这个是图片的访问路径
STATIC_URL = 'static/'

# 需要配置一下我们的文件所在路径(文件夹)
STATICFILES_DIRS = [
    str(BASE_DIR / "static"),
]

IMAGE_URL = 'http://localhost:8000/static/product_images/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 全局的token验证配置
JWT_EXPIRE_TIME = 3600

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "utils.JWTAuth.JWTHeaderQueryParamAuthentication"
    ],
    "EXCEPTION_HANDLER": "utils.exceptions.custom_exception_handler",
}

# 支付宝配置信息
APPID = "9021000158671301"
ALI_PUB_KEY_PATH = BASE_DIR / "apps/pay/keys/alipay_key.txt"
PRIVATE_KEY_PATH = BASE_DIR / "apps/pay/keys/private_key.txt"
# 异步接收rul  post请求
APP_NOTIFY_URL = "http://127.0.0.1:8000/pay/alipay/return"
# 同步接收url，就是用户在页面上支付成功之后，然后就跳转的页面  get请求
RETURN_URL = "http://127.0.0.1:8000/pay/alipay/return"
# 是否是开发环境
ALIPAY_DEBUG = True

"""
http://127.0.0.1:8000/pay/alipay/return?
charset=utf-8&
out_trade_no=1766369827924&
method=alipay.trade.page.pay.return&
total_amount=438.90&
sign=QNBiko9vUMVH5POvoSXCAmsU5ITq6KG93XEyqaJmSnMaSwkAk0NqAQjT%2FZIGtQ5wS8gGRCyClSr8UEpXVrhv7O8L9fqQxwjkfmWHLQtrd88DDwTSQWQuqIGBB8CcHpI%2F9BCKBZ4H6iVAaMQNZj4wjy%2BReQBfYh0qV2d9D8N%2FyKYYB2RC555VpVPgUMUkryoWbFHbyuudyHbaJY0q3oXzj6t4OnWcpVkhGRR4r%2B80a%2BXl8ISGIAQiYHP%2BhRc8jZCDuGUvG2e5dfT5XHfrb1hVM69T1zw0U4eBZ4QuDzcOHRvsxJ4qyd4b5%2FaYy87TMR75NasOgfslJRHhypSBMl77ag%3D%3D&
trade_no=2025122322001480340510104871&
auth_app_id=9021000158671301&
version=1.0&
app_id=9021000158671301&
sign_type=RSA2&
seller_id=2088721090980334&
timestamp=2025-12-23+16%3A26%3A43
"""
