# Generated by Django 4.2.5 on 2025-12-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('sku_id', models.CharField(max_length=255, unique=True)),
                ('nums', models.IntegerField()),
                ('is_delete', models.IntegerField()),
            ],
            options={
                'db_table': 'shopping_cart',
            },
        ),
    ]
