# Generated by Django 4.2.5 on 2025-11-24 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('sex', models.BooleanField(blank=True, default=None, null=True, verbose_name='性别')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'orm_student',
                'verbose_name_plural': 'orm_student',
                'db_table': 'orm_student',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', verbose_name='个性签名')),
                ('address', models.CharField(max_length=500, verbose_name='家庭住址')),
                ('mobile', models.CharField(max_length=15, verbose_name='紧急联系电话')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='myorm.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': 'orm_student_profile',
                'verbose_name_plural': 'orm_student_profile',
                'db_table': 'orm_student_profile',
            },
        ),
    ]
