# Generated by Django 4.2.5 on 2025-11-24 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myorm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('sex', models.BooleanField(blank=True, default=None, null=True, verbose_name='性别')),
            ],
            options={
                'verbose_name': 'orm_auther',
                'verbose_name_plural': 'orm_auther',
                'db_table': 'orm_auther',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='文章标题')),
                ('content', models.TextField(null=True, verbose_name='文章内容')),
                ('pubdate', models.DateTimeField(null=True, verbose_name='发布时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='article', to='myorm.auther', verbose_name='作者')),
            ],
            options={
                'verbose_name': 'orm_article',
                'verbose_name_plural': 'orm_article',
                'db_table': 'orm_article',
            },
        ),
    ]
