# Generated by Django 4.2.5 on 2025-11-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myorm', '0003_alter_article_auther'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('sex', models.BooleanField(blank=True, default=None, null=True, verbose_name='性别')),
            ],
            options={
                'verbose_name': 'orm_teacher',
                'verbose_name_plural': 'orm_teacher',
                'db_table': 'orm_teacher',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='课程名')),
                ('teacher', models.ManyToManyField(related_name='course', to='myorm.teacher', verbose_name='教师信息')),
            ],
            options={
                'verbose_name': 'orm_course',
                'verbose_name_plural': 'orm_course',
                'db_table': 'orm_course',
            },
        ),
    ]
