# Generated by Django 4.2.5 on 2025-11-24 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myorm', '0004_teacher_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='人名')),
                ('age', models.SmallIntegerField(default=0, verbose_name='年龄')),
                ('friends', models.ManyToManyField(to='myorm.people')),
            ],
            options={
                'verbose_name': 'orm_people',
                'verbose_name_plural': 'orm_people',
                'db_table': 'orm_people',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='地区名')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='son', to='myorm.area')),
            ],
            options={
                'verbose_name': 'orm_area',
                'verbose_name_plural': 'orm_area',
                'db_table': 'orm_area',
            },
        ),
    ]
