# Generated by Django 4.2.5 on 2025-11-25 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myorm', '0005_people_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='城市')),
            ],
            options={
                'verbose_name': 'tb_city',
                'verbose_name_plural': 'tb_city',
                'db_table': 'tb_city',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='姓')),
                ('lastname', models.CharField(max_length=50, verbose_name='名')),
                ('hometown', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_hometown', to='myorm.city', verbose_name='家乡')),
                ('living', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_living', to='myorm.city', verbose_name='居住地')),
                ('visitation', models.ManyToManyField(related_name='person_visitation', to='myorm.city', verbose_name='旅游地')),
            ],
            options={
                'verbose_name': 'tb_person',
                'verbose_name_plural': 'tb_person',
                'db_table': 'tb_person',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='省份')),
            ],
            options={
                'verbose_name': 'tb_province',
                'verbose_name_plural': 'tb_province',
                'db_table': 'tb_province',
            },
        ),
        migrations.CreateModel(
            name='PersonProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=20, verbose_name='联系电话')),
                ('wechat', models.CharField(max_length=50, verbose_name='微信号')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='myorm.person')),
            ],
            options={
                'verbose_name': 'tb_person_profile',
                'verbose_name_plural': 'tb_person_profile',
                'db_table': 'tb_person_profile',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city', to='myorm.province', verbose_name='省份'),
        ),
    ]
