# Generated by Django 4.2.5 on 2025-12-02 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('signer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('telphone', models.CharField(blank=True, max_length=255, null=True)),
                ('signer_address', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('default', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_address',
            },
        ),
    ]
