# Generated by Django 4.2.5 on 2025-11-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='软件名称')),
                ('version', models.CharField(max_length=50, verbose_name='版本号')),
                ('website', models.CharField(max_length=500, verbose_name='官方网站')),
                ('picture', models.ImageField(upload_to='picture/%Y/%m/%d/', verbose_name='缩略图')),
                ('downloads', models.FileField(max_length=255, upload_to='soft/%Y/%m/%d/', verbose_name='下载地址')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'tb_software',
                'verbose_name_plural': 'tb_software',
                'db_table': 'tb_software',
            },
        ),
    ]
