# Generated by Django 4.2.5 on 2025-11-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('sex', models.BooleanField(default=True, verbose_name='性别')),
                ('mobile', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='手机号')),
                ('status', models.IntegerField(choices=[(0, '未毕业'), (1, '未入学'), (2, '已毕业')], default=0, verbose_name='状态')),
                ('description', models.TextField(blank=True, null=True, verbose_name='个性签名')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
                'db_table': '学生',
            },
        ),
    ]
