# Generated by Django 4.2.5 on 2025-11-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classmate',
            field=models.CharField(db_column='class', db_index=True, default='', max_length=50, verbose_name='班级编号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.IntegerField(choices=[(0, '未毕业'), (1, '未入学'), (2, '已毕业')], default=0, verbose_name='毕业状态'),
        ),
    ]
