# Generated by Django 4.2.5 on 2025-11-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_created_time_student_updated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='手机号'),
        ),
    ]
