# Generated by Django 4.2.5 on 2025-11-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.BooleanField(choices=[(True, '男'), (False, '女')], default=True, verbose_name='性别'),
        ),
    ]
