# Generated by Django 4.2.5 on 2025-11-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_student_id_alter_student_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='姓名'),
        ),
    ]
